# Generated by Django 4.1.4 on 2022-12-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='articles',
            new_name='scopes',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='tag',
        ),
    ]
