# Generated by Django 3.1.2 on 2022-12-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20221217_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
